Repository TGLuis/Youpidapp, pull requests merged in 2021-02, with the labels that each got.

#29 refactor appbar - fix #20
  app/src/main/java/fragments/AboutFragment.kt
  app/src/main/java/fragments/BoiteFragment.kt
  app/src/main/java/fragments/MainFragment.kt
  app/src/main/java/fragments/MyFragment.kt
  app/src/main/java/lufra/youpidapp/ActionBarButtons.kt
  app/src/main/java/lufra/youpidapp/MainActivity.kt
Labels: refactor

#33 Added pitch to reading and added parameters to screens
  app/build.gradle
  app/src/main/java/fragments/AboutFragment.kt
  app/src/main/java/fragments/BoiteFragment.kt
  app/src/main/java/fragments/MainFragment.kt
  app/src/main/java/fragments/MyFragment.kt
  app/src/main/java/fragments/ParameterFragment.kt
  app/src/main/java/lufra/youpidapp/ActionBarButtons.kt
  app/src/main/java/lufra/youpidapp/Discotheque.kt
  app/src/main/java/lufra/youpidapp/Helper.kt
  app/src/main/java/lufra/youpidapp/MainActivity.kt
  app/src/main/res/drawable/ic_baseline_settings_24.xml
  app/src/main/res/layout/fragment_parameters.xml
  app/src/main/res/layout/simple_spinner_input.xml
  app/src/main/res/values/dimension.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, stupid as fuck

#37 refactor enum PlayType.kt
  app/src/main/java/fragments/BoiteFragment.kt
  app/src/main/java/fragments/ParameterFragment.kt
  app/src/main/java/lufra/youpidapp/ActionBarButtons.kt
  app/src/main/java/lufra/youpidapp/Discotheque.kt
  app/src/main/java/lufra/youpidapp/Helper.kt
  app/src/main/java/lufra/youpidapp/MainActivity.kt
  app/src/main/java/lufra/youpidapp/PlayType.kt
  app/src/main/res/layout/fragment_boite.xml
Labels: refactor

#36 Search/filter operates on transcripts too
  app/src/main/java/adapter/SoundAdapter.kt
  app/src/main/java/data/Sound.kt
  app/src/main/java/lufra/youpidapp/ConfigActivity.kt
  app/src/main/java/lufra/youpidapp/Helper.kt
Labels: enhancement

#41 Shared Preferences and import optimization
  app/src/main/java/fragments/BoiteFragment.kt
  app/src/main/java/fragments/ParameterFragment.kt
  app/src/main/java/lufra/youpidapp/ActionBarButtons.kt
  app/src/main/java/lufra/youpidapp/Discotheque.kt
  app/src/main/java/lufra/youpidapp/Helper.kt
  app/src/main/java/lufra/youpidapp/MainActivity.kt
Labels: enhancement, refactor

#43 Favoris shared preferences side oh yeah just like that
  app/src/main/java/adapter/SoundAdapter.kt
  app/src/main/java/data/Sound.kt
  app/src/main/java/fragments/FavoritesFragment.kt
  app/src/main/java/fragments/MainFragment.kt
  app/src/main/java/lufra/youpidapp/Helper.kt
  app/src/main/java/lufra/youpidapp/MainActivity.kt
  app/src/main/java/lufra/youpidapp/MyDatabase.kt
  app/src/main/res/drawable/ic_baseline_star_24.xml
  app/src/main/res/drawable/ic_baseline_star_border_24.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/sound_button.xml
  app/src/main/res/values/strings.xml
Labels: enhancement
